openapi: 3.0.1
info:
  title: Conferencems API
  description: Conferencems API documentation
  termsOfService: NOOP
  version: 0.0.1
servers:
  - url: http://localhost:8081
    description: Generated server url
security:
  - security_oauth: []
paths:
  /api/conferences/{id}:
    get:
      tags:
        - conference-resource
      operationId: getConference
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ConferenceDTO'
    put:
      tags:
        - conference-resource
      operationId: updateConference
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConferenceDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ConferenceDTO'
    delete:
      tags:
        - conference-resource
      operationId: deleteConference
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    patch:
      tags:
        - conference-resource
      operationId: partialUpdateConference
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConferenceDTO'
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/ConferenceDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ConferenceDTO'
  /api/conferences:
    get:
      tags:
        - conference-resource
      operationId: getAllConferences
      parameters:
        - name: page
          in: query
          description: Zero-based page index (0..N)
          required: false
          schema:
            minimum: 0
            type: integer
            default: 0
        - name: size
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            minimum: 1
            type: integer
            default: 20
        - name: sort
          in: query
          description: >-
            Sorting criteria in the format: property,(asc|desc). Default sort
            order is ascending. Multiple sort criteria are supported.
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConferenceDTO'
    post:
      tags:
        - conference-resource
      operationId: createConference
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConferenceDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ConferenceDTO'
components:
  schemas:
    ConferenceDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        location:
          type: string
  securitySchemes:
    security_oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: >-
            http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth
          tokenUrl: >-
            http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token
          scopes: {}
