# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  conferencego-app:
    image: conferencego
    environment:
      - POSTGRES_HOST=conferencems-postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=conferencems
      - POSTGRES_USER=conferencems
      - KEYCLOAK_REALM=jhipster
      - KEYCLOAK_AUTH_URL=http://keycloak:9080/auth
      - KEYCLOAK_CLIENT_ID=account
  conferencems-postgresql:
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/jhipster/conferencems/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=conferencems
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
